### PR TITLE
Attempt to fix tests

### PR DESCRIPTION
**Pull request by ticosax**

### CODE REVIEW

**Comment by lorenzomorandini** [comment]
Hi @MRigal any new on this?

**Comment by ticosax** [comment]
@lorenzomorandini you can also provide a review I believe.

**Review by lorenzomorandini — APPROVED** [review]
I confirm that with the changes in this PR I was able to run the tests following the instructions in the README (previously they would fail).

**Comment by ticosax** [comment]
I still can't merge it.
I don't know how to unblock this PR.
image

**Comment by lorenzomorandini** [comment]
Just a little above it says that a review is required from someone that has **write access**. Since you have it, are you sure you can not do it on your own?

immagine

**Comment by ticosax** [comment]
I can not approve my own PR. It's a bottleneck in the current permission system as it is currently configured for django-fsm-log. I will ask jazzband roadies what they recommend.

**Review by hugovk — APPROVED** [review]

**Comment by ticosax** [comment]
Thanks @hugovk

**Pull request merged**
