### PR TITLE
Add complex pre-commit including flake8, isort and black

### LINKED ISSUE #118: Add flake8 integration

### PR DESCRIPTION
**Pull request by MRigal**
Fixes #118 #116 #115 

Removed flake8 as separate test as it is now done through pre-commit.ci.
Also adjusted the match between python and django versions based on the official django docs.
Also fixed a warning for appconfig in upcoming version.

### CODE REVIEW

**Comment by MRigal** [comment]
@ticosax I'm wondering about the lack of content at https://app.codecov.io/gh/jazzband/django-fsm-log/
Is it because I'm not allowed to see it or are we possibly missing the token in the repo settings?

**Review by ticosax — APPROVED** [review]
Love it, thanks

**Comment by ticosax** [comment]
> @ticosax I'm wondering about the lack of content at https://app.codecov.io/gh/jazzband/django-fsm-log/ Is it because I'm not allowed to see it or are we possibly missing the token in the repo settings?

I think, after the rebase it should be fixed.

**Comment by ticosax** [comment]
Closing in favor of #123

**Pull request closed without merging**
