### PR TITLE
Fix RemovedInDjango41Warning for default_app_config

### PR DESCRIPTION
**Pull request by blueyed**
Django 4.0 warns about it already:

> django.utils.deprecation.RemovedInDjango41Warning: 'django_fsm_log'
defines default_app_config =
'django_fsm_log.apps.DjangoFSMLogAppConfig'. Django now detects this
configuration automatically. You can remove default_app_config.

Note that the tests apparently do not trigger it, but projects using it
might.

### CODE REVIEW

**Comment by MRigal** [comment]
@blueyed yes, it is already in there... Therefore I don't know why this PR...

**Comment by blueyed** [comment]
> @blueyed yes, it is already in there... Therefore I don't know why this PR...

Django 4.0 will emit a warning already.
I think this PR is fine, but wanted to confirm if there was a specific reason for the lower version you've checked.  Maybe you've meant `<=` also.. anyway, it will prevent an error, but it is good to not emit a warning in the first place - unless I am misunderstanding that Django 4.0 does not handle it properly already, but the warning says it works already.

**Comment by MRigal** [comment]
Django 3.2 supports the feature, so we check if lower than 3.2, which indeed includes also 4.0.
3.2 does not emit a warning but has the feature (https://docs.djangoproject.com/en/4.0/releases/3.2/#automatic-appconfig-discovery), so I don't know why we should change it.

Maybe you thought we only check against 4.1 or misread something?

**Review by MRigal — CHANGES_REQUESTED** [review]
This only changes the behavior for version 3.2, which works well with both versions. I see no reason to change this line.

**Comment by blueyed** [comment]
It triggers the warning when using Django 4.0.
I have a test suite where those warnings get not only displayed/triggered, but also cause an error (so I really get notified about them).  In this case here it was meant to be handled already, but the version check was not fully working as expected.
Or do you actually want to trigger the warning with Django 4.0, which I cannot imagine really.

**Comment by MRigal** [comment]
@blueyed maybe you are not using the actual version in your project. 

The code as it is right now, won't trigger the warning with Django 4.0. Your change only impacts the version 3.2, which as I said, accept both variants, without triggering a warning.

**Comment by blueyed** [comment]
@MRigal 
Oh, you are correct.  I've likely have seen it when the last released version, and then have not checked if that code was included already.  And after all your code is more strict.
Thanks for you your persistence.. :)

**Pull request closed without merging**
